### ISSUE TITLE
epicsExit available on windows?

### ISSUE THREAD

**Issue by thomascobb** [mdavidsaver/epicscorelibs#11]
It would appear that ctypes can't find epicsExit on windows. Is this expected?

Here's the stack track (where dbCore is imported from epicscorelibs.ioc):
```
   Traceback (most recent call last):
    File "D:\a\pythonIoc\pythonIoc\tests\sim_records.py", line 7, in <module>
      from softioc import softioc
    File "c:\users\runneradmin\appdata\local\temp\tmp7osbhxx2\lib\site-packages\softioc\softioc.py", line 9, in <module>
      from . import imports
    File "c:\users\runneradmin\appdata\local\temp\tmp7osbhxx2\lib\site-packages\softioc\imports.py", line 103, in <module>
      epicsExit = dbCore.epicsExit
    File "C:\cibw\python\python.3.8.9\tools\lib\ctypes\__init__.py", line 386, in __getattr__
      func = self.__getitem__(name)
    File "C:\cibw\python\python.3.8.9\tools\lib\ctypes\__init__.py", line 391, in __getitem__
      func = self._FuncPtr((name_or_ordinal, self))
  AttributeError: function 'epicsExit' not found
```
Heres the CI run:
https://github.com/dls-controls/pythonIoc/runs/2555462097?check_suite_focus=true

**Comment by mdavidsaver** [comment]
Try `Com.epicsExit`.  `dbCore.epicsExit` works on Linux where symbol lookup is based around "address space", which contains a library and its dependencies.  On Windows, lookup is based on object file (exe or dll), and does not search dependencies.

**Comment by thomascobb** [comment]
What about `eltc`? I did a grep in all the .so files in epicscorelibs linux build but can't find it...

**Comment by thomascobb** [comment]
scratch that, its in libCom...
